# Generated by Django 5.1.3 on 2024-12-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.company'),
        ),
        migrations.AddField(
            model_name='form',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='api.company'),
        ),
        migrations.AddField(
            model_name='formdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_data', to='api.company'),
        ),
        migrations.AddField(
            model_name='formfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_files', to='api.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='api.company'),
        ),
    ]
