# Generated by Django 5.1.3 on 2024-12-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
