# Generated by Django 5.1.3 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calendar_company_form_company_formdata_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
