# Generated by Django 5.1.2 on 2024-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
