# Generated by Django 5.1.3 on 2024-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calendar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='meeting_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
