# Generated by Django 5.1.3 on 2024-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calendar_meeting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
