# Generated by Django 5.1.2 on 2024-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_form_create_at_form_create_date_form_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
