# Generated by Django 5.1.3 on 2024-12-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='event_type',
            field=models.CharField(choices=[('NONE', 'None'), ('CUSM', 'Customer Meeting'), ('SCAL', 'Sales Call'), ('FLUP', 'Follow-Up'), ('PDEM', 'Product Demo'), ('PDIS', 'Proposal Discussion'), ('CSNG', 'Contract Signing'), ('FSES', 'Feedback Session'), ('TSES', 'Training Session'), ('NEVT', 'Networking Event'), ('LQCL', 'Lead Qualification Call'), ('OSES', 'Onboarding Session'), ('CLCH', 'Campaign Launch'), ('SUCL', 'Support Call'), ('CARY', 'Customer Anniversary'), ('RREM', 'Renewal Reminder'), ('CSSY', 'Customer Satisfaction Survey'), ('TMTG', 'Team Meeting'), ('GLRW', 'Goal Review'), ('PERW', 'Performance Review'), ('PPDN', 'Partnership Discussion'), ('BDAY', 'Birthday')], default='none', max_length=28),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'None'), ('DALY', 'Daily'), ('WEEK', 'Weekly'), ('MONT', 'Monthly'), ('YEAR', 'Yearly')], default='none', max_length=10),
        ),
    ]
