# Generated by Django 5.1.2 on 2024-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_form_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
