# Generated by Django 5.1.2 on 2024-11-29 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_form_create_date_alter_form_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_data', models.JSONField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('create_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_data', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.form')),
                ('update_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
