# Generated by Django 5.1.2 on 2024-11-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_formdata_audio_formdata_photo_formdata_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='video',
        ),
        migrations.CreateModel(
            name='FormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(max_length=20)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.formdata')),
            ],
        ),
    ]
