# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.protos import sample_pb2 as api_dot_protos_dot_sample__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api/protos/sample_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OTPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateOTP = channel.unary_unary(
                '/OTPService/GenerateOTP',
                request_serializer=api_dot_protos_dot_sample__pb2.OTPRequest.SerializeToString,
                response_deserializer=api_dot_protos_dot_sample__pb2.OTPResponse.FromString,
                _registered_method=True)
        self.ValidateOTP = channel.unary_unary(
                '/OTPService/ValidateOTP',
                request_serializer=api_dot_protos_dot_sample__pb2.OTPValidationRequest.SerializeToString,
                response_deserializer=api_dot_protos_dot_sample__pb2.OTPValidationResponse.FromString,
                _registered_method=True)


class OTPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OTPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateOTP,
                    request_deserializer=api_dot_protos_dot_sample__pb2.OTPRequest.FromString,
                    response_serializer=api_dot_protos_dot_sample__pb2.OTPResponse.SerializeToString,
            ),
            'ValidateOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateOTP,
                    request_deserializer=api_dot_protos_dot_sample__pb2.OTPValidationRequest.FromString,
                    response_serializer=api_dot_protos_dot_sample__pb2.OTPValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OTPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OTPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OTPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OTPService/GenerateOTP',
            api_dot_protos_dot_sample__pb2.OTPRequest.SerializeToString,
            api_dot_protos_dot_sample__pb2.OTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OTPService/ValidateOTP',
            api_dot_protos_dot_sample__pb2.OTPValidationRequest.SerializeToString,
            api_dot_protos_dot_sample__pb2.OTPValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
